FROM node:13.6.0-alpine3.10

RUN mkdir -p /usr/src/telstradev
WORKDIR /urs/src/telstradev
COPY . .

RUN npm install
RUN npm link

RUN npm link /urs/src/telstradev

RUN npm run build

CMD node test.js