/**
 * Telstra Messaging API
 * The Telstra Messaging API specification
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeleteNumberRequest model module.
 * @module model/DeleteNumberRequest
 * @version 1.0.8
 */
class DeleteNumberRequest {
    /**
     * Constructs a new <code>DeleteNumberRequest</code>.
     * @alias module:model/DeleteNumberRequest
     */
    constructor() { 
        
        DeleteNumberRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DeleteNumberRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeleteNumberRequest} obj Optional instance to populate.
     * @return {module:model/DeleteNumberRequest} The populated <code>DeleteNumberRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeleteNumberRequest();

            if (data.hasOwnProperty('emptyArr')) {
                obj['emptyArr'] = ApiClient.convertToType(data['emptyArr'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Empty Arr
 * @member {Number} emptyArr
 * @default 0
 */
DeleteNumberRequest.prototype['emptyArr'] = 0;






export default DeleteNumberRequest;

