/**
 * Telstra Messaging API
 * The API specification for Telstra Messaging API
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MMSContent from './MMSContent';

/**
 * The GetMmsResponse model module.
 * @module model/GetMmsResponse
 * @version 1.0.8
 */
class GetMmsResponse {
    /**
     * Constructs a new <code>GetMmsResponse</code>.
     * @alias module:model/GetMmsResponse
     * @param status {String} The final state of the message. 
     * @param destinationAddress {String} The number the message was sent to. 
     * @param senderAddress {String} The number the message was sent from. 
     * @param sentTimestamp {String} Time handling of the message ended. 
     * @param mMSContent {Array.<module:model/MMSContent>} An array of content that was received in an MMS message. 
     */
    constructor(status, destinationAddress, senderAddress, sentTimestamp, mMSContent) { 
        
        GetMmsResponse.initialize(this, status, destinationAddress, senderAddress, sentTimestamp, mMSContent);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status, destinationAddress, senderAddress, sentTimestamp, mMSContent) { 
        obj['status'] = status;
        obj['destinationAddress'] = destinationAddress;
        obj['senderAddress'] = senderAddress;
        obj['sentTimestamp'] = sentTimestamp;
        obj['MMSContent'] = mMSContent;
    }

    /**
     * Constructs a <code>GetMmsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetMmsResponse} obj Optional instance to populate.
     * @return {module:model/GetMmsResponse} The populated <code>GetMmsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetMmsResponse();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('destinationAddress')) {
                obj['destinationAddress'] = ApiClient.convertToType(data['destinationAddress'], 'String');
            }
            if (data.hasOwnProperty('senderAddress')) {
                obj['senderAddress'] = ApiClient.convertToType(data['senderAddress'], 'String');
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
            if (data.hasOwnProperty('messageId')) {
                obj['messageId'] = ApiClient.convertToType(data['messageId'], 'String');
            }
            if (data.hasOwnProperty('apiMsgId')) {
                obj['apiMsgId'] = ApiClient.convertToType(data['apiMsgId'], 'String');
            }
            if (data.hasOwnProperty('sentTimestamp')) {
                obj['sentTimestamp'] = ApiClient.convertToType(data['sentTimestamp'], 'String');
            }
            if (data.hasOwnProperty('MMSContent')) {
                obj['MMSContent'] = ApiClient.convertToType(data['MMSContent'], [MMSContent]);
            }
        }
        return obj;
    }


}

/**
 * The final state of the message. 
 * @member {String} status
 */
GetMmsResponse.prototype['status'] = undefined;

/**
 * The number the message was sent to. 
 * @member {String} destinationAddress
 */
GetMmsResponse.prototype['destinationAddress'] = undefined;

/**
 * The number the message was sent from. 
 * @member {String} senderAddress
 */
GetMmsResponse.prototype['senderAddress'] = undefined;

/**
 * The subject assigned to the message. 
 * @member {String} subject
 */
GetMmsResponse.prototype['subject'] = undefined;

/**
 * Message Id assigned by the MMSC. 
 * @member {String} messageId
 */
GetMmsResponse.prototype['messageId'] = undefined;

/**
 * Message Id assigned by the API. 
 * @member {String} apiMsgId
 */
GetMmsResponse.prototype['apiMsgId'] = undefined;

/**
 * Time handling of the message ended. 
 * @member {String} sentTimestamp
 */
GetMmsResponse.prototype['sentTimestamp'] = undefined;

/**
 * An array of content that was received in an MMS message. 
 * @member {Array.<module:model/MMSContent>} MMSContent
 */
GetMmsResponse.prototype['MMSContent'] = undefined;






export default GetMmsResponse;

