/**
 * Telstra Messaging API
 * The Telstra Messaging API specification
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetSubscriptionResponse model module.
 * @module model/GetSubscriptionResponse
 * @version 1.0.8
 */
class GetSubscriptionResponse {
    /**
     * Constructs a new <code>GetSubscriptionResponse</code>.
     * @alias module:model/GetSubscriptionResponse
     */
    constructor() { 
        
        GetSubscriptionResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetSubscriptionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetSubscriptionResponse} obj Optional instance to populate.
     * @return {module:model/GetSubscriptionResponse} The populated <code>GetSubscriptionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetSubscriptionResponse();

            if (data.hasOwnProperty('activeDays')) {
                obj['activeDays'] = ApiClient.convertToType(data['activeDays'], 'String');
            }
            if (data.hasOwnProperty('notifyURL')) {
                obj['notifyURL'] = ApiClient.convertToType(data['notifyURL'], 'String');
            }
            if (data.hasOwnProperty('destinationAddress')) {
                obj['destinationAddress'] = ApiClient.convertToType(data['destinationAddress'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Number of active days
 * @member {String} activeDays
 */
GetSubscriptionResponse.prototype['activeDays'] = undefined;

/**
 * Notify url configured
 * @member {String} notifyURL
 */
GetSubscriptionResponse.prototype['notifyURL'] = undefined;

/**
 * The mobile phone number that was allocated
 * @member {String} destinationAddress
 */
GetSubscriptionResponse.prototype['destinationAddress'] = undefined;






export default GetSubscriptionResponse;

