/**
 * Telstra Messaging API
 * The Telstra Messaging API specification
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InboundPollResponse model module.
 * @module model/InboundPollResponse
 * @version 1.0.8
 */
class InboundPollResponse {
    /**
     * Constructs a new <code>InboundPollResponse</code>.
     * Poll for incoming messages returning the latest. Only works if no callback url was specified when provisioning a number. 
     * @alias module:model/InboundPollResponse
     */
    constructor() { 
        
        InboundPollResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InboundPollResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InboundPollResponse} obj Optional instance to populate.
     * @return {module:model/InboundPollResponse} The populated <code>InboundPollResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InboundPollResponse();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('destinationAddress')) {
                obj['destinationAddress'] = ApiClient.convertToType(data['destinationAddress'], 'String');
            }
            if (data.hasOwnProperty('senderAddress')) {
                obj['senderAddress'] = ApiClient.convertToType(data['senderAddress'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('messageId')) {
                obj['messageId'] = ApiClient.convertToType(data['messageId'], 'String');
            }
            if (data.hasOwnProperty('sentTimestamp')) {
                obj['sentTimestamp'] = ApiClient.convertToType(data['sentTimestamp'], 'String');
            }
        }
        return obj;
    }


}

/**
 * message status
 * @member {String} status
 */
InboundPollResponse.prototype['status'] = undefined;

/**
 * The phone number (recipient) that the message was sent to (in E.164 format). 
 * @member {String} destinationAddress
 */
InboundPollResponse.prototype['destinationAddress'] = undefined;

/**
 * The phone number (sender) that the message was sent from (in E.164 format). 
 * @member {String} senderAddress
 */
InboundPollResponse.prototype['senderAddress'] = undefined;

/**
 * Text of the message that was sent
 * @member {String} message
 */
InboundPollResponse.prototype['message'] = undefined;

/**
 * Message Id
 * @member {String} messageId
 */
InboundPollResponse.prototype['messageId'] = undefined;

/**
 * The date and time when the message was sent by recipient.
 * @member {String} sentTimestamp
 */
InboundPollResponse.prototype['sentTimestamp'] = undefined;






export default InboundPollResponse;

