/**
 * Telstra Messaging API
 * The Telstra Messaging API specification
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Message from './Message';

/**
 * The MessageSentResponseSms model module.
 * @module model/MessageSentResponseSms
 * @version 1.0.8
 */
class MessageSentResponseSms {
    /**
     * Constructs a new <code>MessageSentResponseSms</code>.
     * @alias module:model/MessageSentResponseSms
     * @param messages {Array.<module:model/Message>} An array of messages.
     * @param messageType {String} This returns whether the message sent was a SMS or MMS.
     * @param numberSegments {Number} A message which has 160 GSM-7 characters or less will have numberSegments=1. Note that multi-part messages which are over 160 GSM-7 characters will include the User Data Header as part of the numberSegments. The User Data Header is being used for the re-assembly of the messages. 
     */
    constructor(messages, messageType, numberSegments) { 
        
        MessageSentResponseSms.initialize(this, messages, messageType, numberSegments);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, messages, messageType, numberSegments) { 
        obj['messages'] = messages;
        obj['messageType'] = messageType;
        obj['numberSegments'] = numberSegments;
    }

    /**
     * Constructs a <code>MessageSentResponseSms</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessageSentResponseSms} obj Optional instance to populate.
     * @return {module:model/MessageSentResponseSms} The populated <code>MessageSentResponseSms</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessageSentResponseSms();

            if (data.hasOwnProperty('messages')) {
                obj['messages'] = ApiClient.convertToType(data['messages'], [Message]);
            }
            if (data.hasOwnProperty('Country')) {
                obj['Country'] = ApiClient.convertToType(data['Country'], [Object]);
            }
            if (data.hasOwnProperty('messageType')) {
                obj['messageType'] = ApiClient.convertToType(data['messageType'], 'String');
            }
            if (data.hasOwnProperty('numberSegments')) {
                obj['numberSegments'] = ApiClient.convertToType(data['numberSegments'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * An array of messages.
 * @member {Array.<module:model/Message>} messages
 */
MessageSentResponseSms.prototype['messages'] = undefined;

/**
 * An array of the countries to which the destination MSISDNs belong.
 * @member {Array.<Object>} Country
 */
MessageSentResponseSms.prototype['Country'] = undefined;

/**
 * This returns whether the message sent was a SMS or MMS.
 * @member {String} messageType
 */
MessageSentResponseSms.prototype['messageType'] = undefined;

/**
 * A message which has 160 GSM-7 characters or less will have numberSegments=1. Note that multi-part messages which are over 160 GSM-7 characters will include the User Data Header as part of the numberSegments. The User Data Header is being used for the re-assembly of the messages. 
 * @member {Number} numberSegments
 */
MessageSentResponseSms.prototype['numberSegments'] = undefined;






export default MessageSentResponseSms;

