/**
 * Telstra Messaging API
 * The API specification for Telstra Messaging API
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OAuthResponse model module.
 * @module model/OAuthResponse
 * @version 1.0.8
 */
class OAuthResponse {
    /**
     * Constructs a new <code>OAuthResponse</code>.
     * @alias module:model/OAuthResponse
     */
    constructor() { 
        
        OAuthResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OAuthResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OAuthResponse} obj Optional instance to populate.
     * @return {module:model/OAuthResponse} The populated <code>OAuthResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OAuthResponse();

            if (data.hasOwnProperty('access_token')) {
                obj['access_token'] = ApiClient.convertToType(data['access_token'], 'String');
            }
            if (data.hasOwnProperty('token_type')) {
                obj['token_type'] = ApiClient.convertToType(data['token_type'], 'String');
            }
            if (data.hasOwnProperty('expires_in')) {
                obj['expires_in'] = ApiClient.convertToType(data['expires_in'], 'String');
            }
        }
        return obj;
    }


}

/**
 * OAuth access token
 * @member {String} access_token
 */
OAuthResponse.prototype['access_token'] = undefined;

/**
 * OAuth token type
 * @member {String} token_type
 */
OAuthResponse.prototype['token_type'] = undefined;

/**
 * OAuth expiry time
 * @member {String} expires_in
 */
OAuthResponse.prototype['expires_in'] = undefined;






export default OAuthResponse;

