/**
 * Telstra Messaging API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Status from './Status';

/**
 * The OutboundPollResponse model module.
 * @module model/OutboundPollResponse
 * @version 2.0.0
 */
class OutboundPollResponse {
    /**
     * Constructs a new <code>OutboundPollResponse</code>.
     * @alias module:model/OutboundPollResponse
     */
    constructor() { 
        
        OutboundPollResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OutboundPollResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OutboundPollResponse} obj Optional instance to populate.
     * @return {module:model/OutboundPollResponse} The populated <code>OutboundPollResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OutboundPollResponse();

            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'String');
            }
            if (data.hasOwnProperty('sentTimestamp')) {
                obj['sentTimestamp'] = ApiClient.convertToType(data['sentTimestamp'], 'String');
            }
            if (data.hasOwnProperty('receivedTimestamp')) {
                obj['receivedTimestamp'] = ApiClient.convertToType(data['receivedTimestamp'], 'String');
            }
            if (data.hasOwnProperty('deliveryStatus')) {
                obj['deliveryStatus'] = Status.constructFromObject(data['deliveryStatus']);
            }
        }
        return obj;
    }


}

/**
 * The phone number (recipient) the message was sent to (in E.164 format). 
 * @member {String} to
 */
OutboundPollResponse.prototype['to'] = undefined;

/**
 * The date and time when the message was sent.
 * @member {String} sentTimestamp
 */
OutboundPollResponse.prototype['sentTimestamp'] = undefined;

/**
 * The date and time when the message was recieved by recipient.
 * @member {String} receivedTimestamp
 */
OutboundPollResponse.prototype['receivedTimestamp'] = undefined;

/**
 * @member {module:model/Status} deliveryStatus
 */
OutboundPollResponse.prototype['deliveryStatus'] = undefined;






export default OutboundPollResponse;

