/**
 * Telstra Messaging API
 * The Telstra Messaging API specification
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProvisionNumberResponse model module.
 * @module model/ProvisionNumberResponse
 * @version 1.0.8
 */
class ProvisionNumberResponse {
    /**
     * Constructs a new <code>ProvisionNumberResponse</code>.
     * @alias module:model/ProvisionNumberResponse
     */
    constructor() { 
        
        ProvisionNumberResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProvisionNumberResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProvisionNumberResponse} obj Optional instance to populate.
     * @return {module:model/ProvisionNumberResponse} The populated <code>ProvisionNumberResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProvisionNumberResponse();

            if (data.hasOwnProperty('destinationAddress')) {
                obj['destinationAddress'] = ApiClient.convertToType(data['destinationAddress'], 'String');
            }
            if (data.hasOwnProperty('expiryDate')) {
                obj['expiryDate'] = ApiClient.convertToType(data['expiryDate'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The mobile phone number that was allocated
 * @member {String} destinationAddress
 */
ProvisionNumberResponse.prototype['destinationAddress'] = undefined;

/**
 * Free Trial apps can only add activeDays for their provisioned number every 30 days. This is in Unix time format.
 * @member {Number} expiryDate
 */
ProvisionNumberResponse.prototype['expiryDate'] = undefined;






export default ProvisionNumberResponse;

