/**
 * Telstra Messaging API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProvisionNumberRequest model module.
 * @module model/ProvisionNumberRequest
 * @version 2.0.0
 */
class ProvisionNumberRequest {
    /**
     * Constructs a new <code>ProvisionNumberRequest</code>.
     * @alias module:model/ProvisionNumberRequest
     */
    constructor() { 
        
        ProvisionNumberRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProvisionNumberRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProvisionNumberRequest} obj Optional instance to populate.
     * @return {module:model/ProvisionNumberRequest} The populated <code>ProvisionNumberRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProvisionNumberRequest();

            if (data.hasOwnProperty('activeDays')) {
                obj['activeDays'] = ApiClient.convertToType(data['activeDays'], 'Number');
            }
            if (data.hasOwnProperty('notifyURL')) {
                obj['notifyURL'] = ApiClient.convertToType(data['notifyURL'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The number of days before for which this number is provisioned. 
 * @member {Number} activeDays
 */
ProvisionNumberRequest.prototype['activeDays'] = undefined;

/**
 * A notification URL that will be POSTed to whenever a new message (i.e. a reply to a message sent) arrives at this destination address.  If this is not provided then you can use the Get /sms or /mms API to poll for reply messages.  If you are using a domain URL you must include the forward slash at the end of the URL (e.g. http://www.example.com/).  *Please note that the notification URLs and the Get /sms or /mms call are exclusive. If a notification URL has been set then the GET call will not provide any useful information.* 
 * @member {String} notifyURL
 */
ProvisionNumberRequest.prototype['notifyURL'] = undefined;






export default ProvisionNumberRequest;

