/**
 * Telstra Messaging API
 * The API specification for Telstra Messaging API
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MessageMulti from './MessageMulti';

/**
 * The SendSmsMultiRequest model module.
 * @module model/SendSmsMultiRequest
 * @version 1.0.8
 */
class SendSmsMultiRequest {
    /**
     * Constructs a new <code>SendSmsMultiRequest</code>.
     * @alias module:model/SendSmsMultiRequest
     */
    constructor() { 
        
        SendSmsMultiRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SendSmsMultiRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendSmsMultiRequest} obj Optional instance to populate.
     * @return {module:model/SendSmsMultiRequest} The populated <code>SendSmsMultiRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendSmsMultiRequest();

            if (data.hasOwnProperty('smsMulti')) {
                obj['smsMulti'] = ApiClient.convertToType(data['smsMulti'], [MessageMulti]);
            }
            if (data.hasOwnProperty('notiyURL')) {
                obj['notiyURL'] = ApiClient.convertToType(data['notiyURL'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Multiple SMS. Up to 10 messages can be sent in one API call.
 * @member {Array.<module:model/MessageMulti>} smsMulti
 */
SendSmsMultiRequest.prototype['smsMulti'] = undefined;

/**
 * Contains a URL that will be called once your message has been processed. The status may be delivered, expired, deleted, etc. Please refer to the Delivery Status section for more information.  If you are using a domain URL you must include the forward slash at the end of the URL (e.g. http://www.example.com/). 
 * @member {String} notiyURL
 */
SendSmsMultiRequest.prototype['notiyURL'] = undefined;






export default SendSmsMultiRequest;

