/**
 * Telstra Messaging API
 * The API specification for Telstra Messaging API
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Status.
* @enum {}
* @readonly
*/
export default class Status {
    
        /**
         * value: "PEND"
         * @const
         */
        "PEND" = "PEND";

    
        /**
         * value: "SENT"
         * @const
         */
        "SENT" = "SENT";

    
        /**
         * value: "DELIVRD"
         * @const
         */
        "DELIVRD" = "DELIVRD";

    
        /**
         * value: "EXPIRED"
         * @const
         */
        "EXPIRED" = "EXPIRED";

    
        /**
         * value: "DELETED"
         * @const
         */
        "DELETED" = "DELETED";

    
        /**
         * value: "UNDVBL"
         * @const
         */
        "UNDVBL" = "UNDVBL";

    
        /**
         * value: "REJECTD"
         * @const
         */
        "REJECTD" = "REJECTD";

    
        /**
         * value: "Unknown"
         * @const
         */
        "Unknown" = "Unknown";

    

    /**
    * Returns a <code>Status</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Status} The enum <code>Status</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

