/**
 * TelstraMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';


const APIException = require('./APIException');

/**
 * Creates an instance of ErrorErrorError62ErrorException
 */
class ErrorErrorError62ErrorException extends APIException {
    /**
     * @constructor
     */
    constructor() {
        super();
        /**
         * A short error code
         */
        this.status = null;

        /**
         * Message describing the error.
         */
        this.message = null;
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'status', realName: 'status' },
            { name: 'message', realName: 'message' },
        ]);
    }
}

module.exports = ErrorErrorError62ErrorException;
