/**
 * TelstraMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of InboundPollResponse
 */
class InboundPollResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.destinationAddress = this.constructor.getValue(obj.destinationAddress);
        this.senderAddress = this.constructor.getValue(obj.senderAddress);
        this.message = this.constructor.getValue(obj.message);
        this.sentTimestamp = this.constructor.getValue(obj.sentTimestamp);
        this.messageId = this.constructor.getValue(obj.messageId);
        this.status = this.constructor.getValue(obj.status);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'destinationAddress', realName: 'destinationAddress' },
            { name: 'senderAddress', realName: 'senderAddress' },
            { name: 'message', realName: 'message' },
            { name: 'sentTimestamp', realName: 'sentTimestamp' },
            { name: 'messageId', realName: 'messageId' },
            { name: 'status', realName: 'status' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = InboundPollResponse;
