/**
 * TelstraMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const OutboundPollResponse = require('../lib/Models/OutboundPollResponse');
const MMSContent = require('../lib/Models/MMSContent');
const SendMMSRequest = require('../lib/Models/SendMMSRequest');
const ErrorError = require('../lib/Models/ErrorError');
const SendSMSRequest = require('../lib/Models/SendSMSRequest');
const InboundPollResponse = require('../lib/Models/InboundPollResponse');
const Message = require('../lib/Models/Message');
const MessageSentResponse = require('../lib/Models/MessageSentResponse');
const ProvisionNumberResponse = require('../lib/Models/ProvisionNumberResponse');
const ProvisionNumberRequest = require('../lib/Models/ProvisionNumberRequest');
const OAuthToken = require('../lib/Models/OAuthToken');
const ErrorErrorError62ErrorException =
  require('../lib/Exceptions/ErrorErrorError62ErrorException');
const ErrorErrorErrorErrorErrorException =
  require('../lib/Exceptions/ErrorErrorErrorErrorErrorException');
const OAuthProviderException = require('../lib/Exceptions/OAuthProviderException');

const classMap = {
    OutboundPollResponse,
    MMSContent,
    SendMMSRequest,
    ErrorError,
    SendSMSRequest,
    InboundPollResponse,
    Message,
    MessageSentResponse,
    ProvisionNumberResponse,
    ProvisionNumberRequest,
    OAuthToken,
    ErrorErrorError62ErrorException,
    ErrorErrorErrorErrorErrorException,
    OAuthProviderException,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
