/**
 * Telstra Messaging API
 *  The Telstra SMS Messaging API allows your applications to send and receive SMS text messages from Australia's leading network operator.  It also allows your application to track the delivery status of both sent and received SMS messages. 
 *
 * OpenAPI spec version: 2.2.4
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TelstraMessaging);
  }
}(this, function(expect, TelstraMessaging) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TelstraMessaging.OutboundPollResponseInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OutboundPollResponseInner', function() {
    it('should create an instance of OutboundPollResponseInner', function() {
      // uncomment below and update the code to test OutboundPollResponseInner
      //var instane = new TelstraMessaging.OutboundPollResponseInner();
      //expect(instance).to.be.a(TelstraMessaging.OutboundPollResponseInner);
    });

    it('should have the property to (base name: "to")', function() {
      // uncomment below and update the code to test the property to
      //var instane = new TelstraMessaging.OutboundPollResponseInner();
      //expect(instance).to.be();
    });

    it('should have the property receivedTimestamp (base name: "receivedTimestamp")', function() {
      // uncomment below and update the code to test the property receivedTimestamp
      //var instane = new TelstraMessaging.OutboundPollResponseInner();
      //expect(instance).to.be();
    });

    it('should have the property sentTimestamp (base name: "sentTimestamp")', function() {
      // uncomment below and update the code to test the property sentTimestamp
      //var instane = new TelstraMessaging.OutboundPollResponseInner();
      //expect(instance).to.be();
    });

    it('should have the property deliveryStatus (base name: "deliveryStatus")', function() {
      // uncomment below and update the code to test the property deliveryStatus
      //var instane = new TelstraMessaging.OutboundPollResponseInner();
      //expect(instance).to.be();
    });

  });

}));
