/**
 * Telstra Messaging API
 * The API specification for Telstra Messaging API
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TelstraMessaging);
  }
}(this, function(expect, TelstraMessaging) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TelstraMessaging.SendSMSRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SendSMSRequest', function() {
    it('should create an instance of SendSMSRequest', function() {
      // uncomment below and update the code to test SendSMSRequest
      //var instane = new TelstraMessaging.SendSMSRequest();
      //expect(instance).to.be.a(TelstraMessaging.SendSMSRequest);
    });

    it('should have the property to (base name: "to")', function() {
      // uncomment below and update the code to test the property to
      //var instane = new TelstraMessaging.SendSMSRequest();
      //expect(instance).to.be();
    });

    it('should have the property body (base name: "body")', function() {
      // uncomment below and update the code to test the property body
      //var instane = new TelstraMessaging.SendSMSRequest();
      //expect(instance).to.be();
    });

    it('should have the property from (base name: "from")', function() {
      // uncomment below and update the code to test the property from
      //var instane = new TelstraMessaging.SendSMSRequest();
      //expect(instance).to.be();
    });

    it('should have the property validity (base name: "validity")', function() {
      // uncomment below and update the code to test the property validity
      //var instane = new TelstraMessaging.SendSMSRequest();
      //expect(instance).to.be();
    });

    it('should have the property scheduledDelivery (base name: "scheduledDelivery")', function() {
      // uncomment below and update the code to test the property scheduledDelivery
      //var instane = new TelstraMessaging.SendSMSRequest();
      //expect(instance).to.be();
    });

    it('should have the property notifyURL (base name: "notifyURL")', function() {
      // uncomment below and update the code to test the property notifyURL
      //var instane = new TelstraMessaging.SendSMSRequest();
      //expect(instance).to.be();
    });

    it('should have the property replyRequest (base name: "replyRequest")', function() {
      // uncomment below and update the code to test the property replyRequest
      //var instane = new TelstraMessaging.SendSMSRequest();
      //expect(instance).to.be();
    });

    it('should have the property priority (base name: "priority")', function() {
      // uncomment below and update the code to test the property priority
      //var instane = new TelstraMessaging.SendSMSRequest();
      //expect(instance).to.be();
    });

  });

}));
