/**
 * Telstra Messaging API
 * The Telstra Messaging API specification
 *
 * The version of the OpenAPI document: 2.2.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import DeleteNumberRequest from './model/DeleteNumberRequest';
import GetMmsResponse from './model/GetMmsResponse';
import GetSubscriptionResponse from './model/GetSubscriptionResponse';
import HealthCheckResponse from './model/HealthCheckResponse';
import InboundPollResponse from './model/InboundPollResponse';
import MMSContent from './model/MMSContent';
import Message from './model/Message';
import MessageMulti from './model/MessageMulti';
import MessageSentResponseMms from './model/MessageSentResponseMms';
import MessageSentResponseSms from './model/MessageSentResponseSms';
import OAuthResponse from './model/OAuthResponse';
import OutboundPollResponse from './model/OutboundPollResponse';
import ProvisionNumberRequest from './model/ProvisionNumberRequest';
import ProvisionNumberResponse from './model/ProvisionNumberResponse';
import SendMmsRequest from './model/SendMmsRequest';
import SendSMSRequest from './model/SendSMSRequest';
import SendSmsMultiRequest from './model/SendSmsMultiRequest';
import Status from './model/Status';
import AuthenticationApi from './api/AuthenticationApi';
import MessagingApi from './api/MessagingApi';
import ProvisioningApi from './api/ProvisioningApi';


/**
* The_Telstra_Messaging_API_specification.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TelstraMessaging = require('index'); // See note below*.
* var xxxSvc = new TelstraMessaging.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TelstraMessaging.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TelstraMessaging.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TelstraMessaging.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.8
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The DeleteNumberRequest model constructor.
     * @property {module:model/DeleteNumberRequest}
     */
    DeleteNumberRequest,

    /**
     * The GetMmsResponse model constructor.
     * @property {module:model/GetMmsResponse}
     */
    GetMmsResponse,

    /**
     * The GetSubscriptionResponse model constructor.
     * @property {module:model/GetSubscriptionResponse}
     */
    GetSubscriptionResponse,

    /**
     * The HealthCheckResponse model constructor.
     * @property {module:model/HealthCheckResponse}
     */
    HealthCheckResponse,

    /**
     * The InboundPollResponse model constructor.
     * @property {module:model/InboundPollResponse}
     */
    InboundPollResponse,

    /**
     * The MMSContent model constructor.
     * @property {module:model/MMSContent}
     */
    MMSContent,

    /**
     * The Message model constructor.
     * @property {module:model/Message}
     */
    Message,

    /**
     * The MessageMulti model constructor.
     * @property {module:model/MessageMulti}
     */
    MessageMulti,

    /**
     * The MessageSentResponseMms model constructor.
     * @property {module:model/MessageSentResponseMms}
     */
    MessageSentResponseMms,

    /**
     * The MessageSentResponseSms model constructor.
     * @property {module:model/MessageSentResponseSms}
     */
    MessageSentResponseSms,

    /**
     * The OAuthResponse model constructor.
     * @property {module:model/OAuthResponse}
     */
    OAuthResponse,

    /**
     * The OutboundPollResponse model constructor.
     * @property {module:model/OutboundPollResponse}
     */
    OutboundPollResponse,

    /**
     * The ProvisionNumberRequest model constructor.
     * @property {module:model/ProvisionNumberRequest}
     */
    ProvisionNumberRequest,

    /**
     * The ProvisionNumberResponse model constructor.
     * @property {module:model/ProvisionNumberResponse}
     */
    ProvisionNumberResponse,

    /**
     * The SendMmsRequest model constructor.
     * @property {module:model/SendMmsRequest}
     */
    SendMmsRequest,

    /**
     * The SendSMSRequest model constructor.
     * @property {module:model/SendSMSRequest}
     */
    SendSMSRequest,

    /**
     * The SendSmsMultiRequest model constructor.
     * @property {module:model/SendSmsMultiRequest}
     */
    SendSmsMultiRequest,

    /**
     * The Status model constructor.
     * @property {module:model/Status}
     */
    Status,

    /**
    * The AuthenticationApi service constructor.
    * @property {module:api/AuthenticationApi}
    */
    AuthenticationApi,

    /**
    * The MessagingApi service constructor.
    * @property {module:api/MessagingApi}
    */
    MessagingApi,

    /**
    * The ProvisioningApi service constructor.
    * @property {module:api/ProvisioningApi}
    */
    ProvisioningApi
};
